theme: jekyll-theme-cayman 
description: "The fourth international workshop on the role of resources in the age of large language models"
basepath: "resourceful-2026/"


navigation:
  - text: Home
    url: /index.html
  - text: Organisation
    url: /organisation.html
