theme: jekyll-theme-cayman 
description: "RESOURCEFUL 2026"
basepath: "resourceful-2026/"


navigation:
  - text: Home
    url: /index.html
  - text: Dates
    url: /dates.html
  - text: Organisation
    url: /oragnisation.html
